# Generated by Django 5.0 on 2025-01-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('source_of_lead', models.CharField(max_length=255)),
                ('campaign_name', models.CharField(max_length=255)),
                ('lead_status', models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold'), ('warm', 'Warm'), ('lost', 'Lost (FIO Order)'), ('not_interested', 'Not Interested')], max_length=20)),
                ('contact_no', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_address', models.TextField()),
                ('date_of_lead', models.DateField()),
                ('visitors_name', models.CharField(max_length=255)),
            ],
        ),
    ]
