# Generated by Django 5.2.3 on 2025-11-01 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crmapp', '0014_remove_quotation_management_contact_by_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('bank_details', models.TextField(blank=True, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('store_address', models.TextField(blank=True, null=True)),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_category', models.CharField(blank=True, max_length=100, null=True)),
                ('GST_details', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='purchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='draft', max_length=100)),
                ('material_Supply', models.CharField(blank=True, max_length=100, null=True)),
                ('quotation_attachment', models.FileField(blank=True, null=True, upload_to='po/quotes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=200)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='batches', to='crmapp.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'batch_no'], name='inventory_p_product_776208_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'batch_no'), name='uq_product_batch'), models.CheckConstraint(condition=models.Q(('expiry_date__isnull', True), ('manufacturing_date__isnull', True), ('expiry_date__gte', models.F('manufacturing_date')), _connector='OR'), name='ck_batch_dates_order')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crmapp.product')),
            ],
            options={
                'indexes': [models.Index(fields=['po'], name='inventory_p_po_id_3657a0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_poi_qty_gt0')],
            },
        ),
    ]
