# Generated by Django 5.2.3 on 2025-11-01 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceiveNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recived_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='recived', max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='inventory.purchaseorder')),
                ('recived_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recived_grns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiveNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_qty', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('received_qty', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('remaining_qty', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.productbatch')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.goodsreceivenote')),
            ],
            options={
                'indexes': [models.Index(fields=['grn'], name='inventory_g_grn_id_c7ca13_idx'), models.Index(fields=['batch'], name='inventory_g_batch_i_bc7571_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('received_qty__gte', 0)), name='ck_grni_recv_ge0')],
            },
        ),
    ]
