# Generated by Django 5.2.3 on 2025-11-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True, null=True)),
                ('bank_details', models.JSONField(blank=True, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('store_address', models.TextField(blank=True, null=True)),
                ('compony_type', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_category', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_details', models.CharField(blank=True, max_length=100, null=True)),
                ('office_poc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('office_poc_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('store_poc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_poc_phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
