# Generated by Django 5.2.3 on 2026-05-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='transaction_type',
            field=models.CharField(choices=[('GRN_IN', 'GRN In'), ('MTN_OUT', 'Material Transfer Out'), ('MTN_IN', 'Material Transfer In'), ('ADJUST', 'Stock Adjustment'), ('SERVICE_OUT', 'Service Consumption'), ('SERVICE_REVERSAL', 'Service Reversal')], max_length=30),
        ),
    ]
