# Generated by Django 5.2.3 on 2026-06-02 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
        ('new_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(max_length=20)),
                ('location_id', models.BigIntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('opening_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('receipt_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('sent_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('approved_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('closing_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.product')),
            ],
            options={
                'unique_together': {('product', 'location_type', 'location_id', 'year', 'month')},
            },
        ),
    ]
