# Generated by Django 5.2.3 on 2025-11-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='bank_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
