# Generated by Django 5.2.3 on 2025-11-27 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0002_batch_site_alter_vendor_bank_details_ho_productbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivenote',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='new_inventory.batch'),
        ),
    ]
