# Generated by Django 5.2.3 on 2026-06-08 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0002_monthlystocksnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challans', to='new_inventory.goodsreceivenote'),
        ),
    ]
