# Generated by Django 5.2.3 on 2025-11-20 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0003_batch_site_ho_productbatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ho',
            old_name='contact_person',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='ho',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ho',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ho', to=settings.AUTH_USER_MODEL),
        ),
    ]
