# Generated by Django 5.2.3 on 2026-06-08 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0003_deliverychallan_grn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='mtn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challan', to='new_inventory.materialtransfernote'),
        ),
    ]
