# Generated by Django 5.2.3 on 2025-11-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0003_goodsreceivenote_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='gst_type',
            field=models.TextField(choices=[('cgst_sgst', 'CGST SGST'), ('igst', 'IGST')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='mode_terms_of_payments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='terms_of_delivery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan_details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
