# Generated by Django 5.2.3 on 2025-11-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0004_purchaseorder_gst_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
