# Generated by Django 5.2.3 on 2025-11-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0004_rename_contact_person_ho_contact_ho_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ho',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
