# Generated by Django 5.2.3 on 2025-11-20 16:19

import django.db.models.deletion
import new_inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_branch_is_head_office'),
        ('new_inventory', '0005_alter_ho_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(default=new_inventory.models.generate_po_no, editable=False, max_length=255, unique=True)),
                ('destination_type', models.CharField(choices=[('BRANCH', 'Branch'), ('HO', 'Head Office'), ('SITE', 'Site')], max_length=20)),
                ('destination_id', models.BigIntegerField()),
                ('status', models.CharField(default='DRAFT', max_length=50)),
                ('material_supply', models.TextField(blank=True, null=True)),
                ('quotation_attachment', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_inventory.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='new_inventory.purchaseorder')),
            ],
        ),
    ]
