# Generated by Django 5.2.3 on 2025-11-29 05:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_branch_is_head_office'),
        ('new_inventory', '0005_purchaseorderitem_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('BRANCH', 'Branch'), ('HO', 'Head Office'), ('SITE', 'Site')], max_length=20)),
                ('location_id', models.BigIntegerField()),
                ('opening_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('in_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('out_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('reserved_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('closing_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='new_inventory.productbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='new_invento_product_cbb7b3_idx'), models.Index(fields=['batch'], name='new_invento_batch_i_864533_idx'), models.Index(fields=['location_type', 'location_id'], name='new_invento_locatio_5e56e3_idx')],
                'unique_together': {('product', 'batch', 'location_type', 'location_id')},
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('BRANCH', 'Branch'), ('HO', 'Head Office'), ('SITE', 'Site')], max_length=20)),
                ('location_id', models.BigIntegerField()),
                ('transaction_type', models.CharField(choices=[('GRN_IN', 'GRN In'), ('MTN_OUT', 'Material Transfer Out'), ('MTN_IN', 'Material Transfer In'), ('ADJUST', 'Stock Adjustment')], max_length=30)),
                ('transaction_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('document_id', models.BigIntegerField(blank=True, null=True)),
                ('in_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('out_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('balance_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='new_inventory.productbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product'], name='new_invento_product_49b6f7_idx'), models.Index(fields=['transaction_date'], name='new_invento_transac_3fc370_idx')],
            },
        ),
    ]
