# Generated by Django 5.2.3 on 2025-11-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0006_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('CLOSED', 'Closed')], default='DRAFT', max_length=50),
        ),
    ]
