# Generated by Django 5.2.3 on 2025-11-29 05:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_branch_is_head_office'),
        ('new_inventory', '0006_currentstock_stockledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('BRANCH', 'Branch'), ('HO', 'Head Office'), ('SITE', 'Site')], max_length=20)),
                ('location_id', models.BigIntegerField()),
                ('total_in_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('total_out_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('total_reserved_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='new_invento_product_2e39b3_idx'), models.Index(fields=['location_type', 'location_id'], name='new_invento_locatio_38f4d9_idx')],
                'unique_together': {('product', 'location_type', 'location_id')},
            },
        ),
    ]
