# Generated by Django 5.2.3 on 2025-12-18 05:21

import django.db.models.deletion
import django.utils.timezone
import new_inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_branch_is_head_office'),
        ('new_inventory', '0007_productstock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTransferNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtn_no', models.CharField(default=new_inventory.models.generate_mtn_no, editable=False, max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('BRANCH', 'Branch'), ('HO', 'Head Office'), ('SITE', 'Site')], max_length=20)),
                ('source_id', models.BigIntegerField()),
                ('destination_type', models.CharField(choices=[('BRANCH', 'Branch'), ('HO', 'Head Office'), ('SITE', 'Site')], max_length=20)),
                ('destination_id', models.BigIntegerField()),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('CLOSED', 'Closed')], default='DRAFT', max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MTNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='new_inventory.productbatch')),
                ('mtn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='new_inventory.materialtransfernote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.product')),
            ],
        ),
    ]
