# Generated by Django 5.2.3 on 2025-11-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0007_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='quotation_attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
