# Generated by Django 5.2.3 on 2025-12-22 06:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_branch_is_head_office'),
        ('new_inventory', '0008_materialtransfernote_mtnitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(max_length=50, unique=True)),
                ('source_type', models.CharField(choices=[('BRANCH', 'Branch'), ('HO', 'Head Office'), ('SITE', 'Site')], default='BRANCH', max_length=20)),
                ('source_id', models.BigIntegerField()),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('approved_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='new_inventory.materialrequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.product')),
            ],
        ),
    ]
