# Generated by Django 5.2.3 on 2025-12-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='pan_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
