# Generated by Django 5.2.3 on 2025-12-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0011_vendor_pan_no_vendor_state_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='pan_no',
        ),
    ]
