# Generated by Django 5.2.3 on 2026-01-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0012_remove_vendor_pan_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='gst_type',
            field=models.CharField(choices=[('no_gst', 'No GST'), ('cgst_sgst', 'CGST+SGST'), ('igst', 'IGST')], default='no_gst', max_length=20),
        ),
    ]
