# Generated by Django 5.2.3 on 2026-01-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0013_alter_purchaseorder_gst_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
