# Generated by Django 5.2.3 on 2026-01-14 07:00

import django.db.models.deletion
import django.utils.timezone
import new_inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_alter_product_standard_unit'),
        ('new_inventory', '0014_purchaseorderitem_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_no', models.CharField(default=new_inventory.models.generate_dc_no, editable=False, max_length=50, unique=True)),
                ('source_type', models.CharField(choices=[('BRANCH', 'Branch'), ('HO', 'Head Office'), ('SITE', 'Site')], max_length=20)),
                ('source_id', models.BigIntegerField()),
                ('destination_type', models.CharField(choices=[('BRANCH', 'Branch'), ('HO', 'Head Office'), ('SITE', 'Site')], max_length=20)),
                ('destination_id', models.BigIntegerField()),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISPATCHED', 'Dispatched')], default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mtn', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challan', to='new_inventory.materialtransfernote')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='new_inventory.productbatch')),
                ('delivery_challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='new_inventory.deliverychallan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.product')),
            ],
        ),
    ]
