# Generated by Django 5.2.3 on 2026-01-16 10:10
# FIXED: compony_type was never a column name; company_type already existed in 0001_initial.
# This migration is now a no-op to preserve the migration graph.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0015_deliverychallan_deliverychallanitem'),
    ]

    operations = [
        # Originally: RenameField vendor.compony_type -> company_type
        # This field never existed under the typo name; the rename was applied
        # directly to the DB outside migrations. No-op here keeps the graph intact.
    ]
