# Generated by Django 5.2.3 on 2026-01-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0015_deliverychallan_deliverychallanitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='compony_type',
            new_name='company_type',
        ),
    ]
