# Generated by Django 5.2.3 on 2026-01-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0016_rename_compony_type_vendor_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='delivery_partner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='delivery_person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='delivery_person_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
