# Generated by Django 4.2 on 2026-05-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0017_deliverychallan_delivery_partner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('product', 'Product'), ('sub_item', 'Sub Item'), ('both', 'Both')], default='product', max_length=20),
        ),
    ]
