# Generated by Django 4.2 on 2026-05-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0025_remove_service_management_status_and_more'),
        ('new_inventory', '0018_vendor_vendor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('sub_item', 'Sub Item')], default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='sub_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.productrequireditem'),
        ),
    ]
