# Generated by Django 4.2 on 2026-05-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0019_purchaseorderitem_item_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='sub_item',
        ),
    ]
