# Generated by Django 4.2 on 2026-05-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0021_purchaseordersubitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseOrderSubItem',
        ),
    ]
