# Generated by Django 4.2 on 2026-05-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0025_remove_service_management_status_and_more'),
        ('new_inventory', '0023_purchaseorderitem_item_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='parent_item',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='sub_item',
        ),
        migrations.CreateModel(
            name='PurchaseOrderSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='new_inventory.purchaseorder')),
                ('sub_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.productrequireditem')),
            ],
        ),
    ]
