# Generated by Django 4.2 on 2026-05-02 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0025_remove_service_management_status_and_more'),
        ('new_inventory', '0024_remove_purchaseorderitem_item_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceiveNoteSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='new_inventory.goodsreceivenote')),
                ('po_sub_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_inventory.purchaseordersubitem')),
                ('sub_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.productrequireditem')),
            ],
        ),
    ]
