# Generated by Django 5.0.7 on 2026-05-09 05:52
# Updated post-merge: standalone migration with no dependency on bharat-new's 0002

from django.db import migrations, models


class Migration(migrations.Migration):

    # This migration is already applied in DB (run_deferred).
    # The dependency on 0002_alter_stockledger_transaction_type was removed
    # because that migration exists only in origin/bharat-new's lineage
    # and is not present in the DB history of this environment.
    dependencies = [
        ('new_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='transaction_type',
            field=models.CharField(
                choices=[
                    ('GRN_IN', 'GRN In'),
                    ('MTN_OUT', 'Material Transfer Out'),
                    ('MTN_IN', 'Material Transfer In'),
                    ('ADJUST', 'Stock Adjustment'),
                    ('SERVICE_OUT', 'Service Deduction'),
                    ('SERVICE_REVERSAL', 'Service Reversal'),
                    ('SERVICE_RETURN', 'Service Stock Return'),
                ],
                max_length=30,
            ),
        ),
    ]
