# Generated by Django 5.0.7 on 2026-05-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0002_alter_stockledger_transaction_type'),
        ('new_inventory', '0026_add_service_out_transaction_type'),
    ]

    operations = [
    ]
