# Generated by Django 5.0.7 on 2026-05-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0027_merge_20260512_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='transaction_type',
            field=models.CharField(choices=[('GRN_IN', 'GRN In'), ('MTN_OUT', 'Material Transfer Out'), ('MTN_IN', 'Material Transfer In'), ('ADJUST', 'Stock Adjustment'), ('SERVICE_OUT', 'Service Deduction'), ('SERVICE_REVERSAL', 'Service Reversal'), ('SERVICE_RETURN', 'Service Stock Return')], max_length=30),
        ),
    ]
