# Generated by Django 5.0.7 on 2026-05-12 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_inventory', '0017_deliverychallan_delivery_partner_name_and_more'),
        ('new_inventory', '0028_alter_stockledger_transaction_type'),
    ]

    operations = [
    ]
