# Generated by Django 5.0 on 2025-05-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='branch',
            field=models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5')], default='NA', max_length=10),
        ),
    ]
