# Generated by Django 5.2.3 on 2026-06-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproductfrequency',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, default=12, help_text='Duration in months', null=True),
        ),
    ]
