# Generated by Django 5.1.1 on 2025-09-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_service_management_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsrecord',
            name='last_alert_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer_details',
            name='primaryemail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
