# Generated by Django 5.2.3 on 2025-11-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_customer_details_branch_lead_management_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_head_office',
            field=models.BooleanField(default=False),
        ),
    ]
