# Generated by Django 5.2.3 on 2026-09-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_serviceproductfrequency_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmanager',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='operationperson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
