# Generated by Django 5.0 on 2025-05-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_lead_management_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='branch',
            field=models.CharField(choices=[('Bhiwandi', 'Bhiwandi'), ('Indore', 'Indore'), ('Hyderabad', 'Hyderabad'), ('Nagpur', 'Nagpur'), ('Amravti', 'Amravti'), ('Aurangabad', 'Aurangabad'), ('Baramati', 'Baramati'), ('Pune', 'Pune')], default='NA', max_length=10),
        ),
    ]
