# Generated by Django 5.1.1 on 2025-10-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_paymentsrecord_last_alert_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
