# Generated by Django 5.2.3 on 2026-09-04 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_branchmanager_is_active_operationperson_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation_management',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='parent_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='crmapp.quotation_management'),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quotation_management',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
