# Generated by Django 5.0 on 2025-05-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_alter_lead_management_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_details',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='customer_details',
            name='lastname',
        ),
    ]
