# Generated by Django 5.2.3 on 2026-09-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_quotation_management_is_latest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproductfrequency',
            name='selected_months',
            field=models.CharField(blank=True, help_text='Selected service months e.g. Jan, Feb, Mar', max_length=255, null=True),
        ),
    ]
