# Generated by Django 5.2.3 on 2025-12-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_alter_lead_management_sourceoflead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='sourceoflead',
            field=models.CharField(choices=[('Google', 'Google'), ('Justdial', 'Justdial'), ('Indiamart', 'IndiaMart'), ('TradeIndia', 'TradeIndia'), ('Renewal', 'Renewal'), ('Customer Reference', 'Customer Reference'), ('BNI', 'BNI'), ('Lionsclub', 'Lions Club'), ('Employee Reference', 'Employee Reference'), ('Others', 'Others')], default='NOT SELECTED', max_length=200),
        ),
    ]
