# Generated by Django 5.1.1 on 2025-10-04 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_product_hsn_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead_management',
            name='branch',
        ),
        migrations.AddField(
            model_name='lead_management',
            name='old_branch',
            field=models.CharField(choices=[('Bhiwandi', 'Bhiwandi'), ('Indore', 'Indore'), ('Hyderabad', 'Hyderabad'), ('Nagpur', 'Nagpur'), ('Amravti', 'Amravti'), ('Aurangabad', 'Aurangabad'), ('Baramati', 'Baramati'), ('Pune', 'Pune')], default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('technician', 'Technician'), ('branch_manager', 'Branch Manager'), ('customer', 'Customer')], max_length=20),
        ),
        migrations.CreateModel(
            name='BranchManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_manager', to='crmapp.branch')),
            ],
        ),
    ]
