# Generated by Django 5.0 on 2025-05-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_rename_firstname_customer_details_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='state',
            field=models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Karnataka', 'Karnataka'), ('Tamil Nadu', 'Tamil Nadu'), ('Rajasthan', 'Rajasthan'), ('Delhi', 'Delhi'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Gujarat', 'Gujarat'), ('West Bengal', 'West Bengal'), ('Madhya Pradesh', 'Madhya Pradesh')], default='Maharashtra', max_length=100),
        ),
    ]
