# Generated by Django 5.2.3 on 2025-12-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_alter_lead_management_sourceoflead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workallocation',
            name='customer_payment_status',
            field=models.CharField(choices=[('Online', 'Online'), ('Cash', 'Cash'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
