# Generated by Django 5.1.1 on 2025-10-04 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_remove_lead_management_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.branch'),
        ),
    ]
