# Generated by Django 5.2.3 on 2026-09-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_serviceproductfrequency_selected_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='or_contact',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer_details',
            name='or_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='or_contact',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='or_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
