# Generated by Django 5.1.1 on 2025-10-07 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_lead_management_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_details', to='crmapp.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesperson',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_person', to='crmapp.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesperson',
            name='co_ordinator',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
