# Generated by Django 5.2.3 on 2025-12-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_alter_workallocation_customer_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workallocation',
            name='customer_payment_status',
            field=models.CharField(choices=[('Online', 'Online'), ('Cash', 'Cash'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
