# Generated by Django 5.2.3 on 2026-09-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_alter_customer_details_or_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='or_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='or_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='or_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
