# Generated by Django 5.2.3 on 2026-01-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0007_alter_workallocation_customer_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='standard_unit',
            field=models.CharField(blank=True, choices=[('Nos', 'Nos'), ('Kg', 'Kg'), ('Gram', 'Gram'), ('Liter', 'Liter'), ('ML', 'ML'), ('Box', 'Box'), ('Packet', 'Packet'), ('Set', 'Set'), ('Dozen', 'Dozen'), ('Meter', 'Meter'), ('Feet', 'Feet'), ('Roll', 'Roll')], max_length=20, null=True),
        ),
    ]
