# Generated by Django 5.2.3 on 2026-09-22 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0004_amcservicevisit_complaint_reason_and_more'),
        ('crmapp', '0007_customer_details_or_email_lead_management_or_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='complaint_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service_management',
            name='complaint_reported_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service_management',
            name='is_complaint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service_management',
            name='parent_amc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_services', to='amc.amccontract'),
        ),
        migrations.AddField(
            model_name='service_management',
            name='parent_amc_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_services', to='amc.amcservicevisit'),
        ),
        migrations.AddField(
            model_name='service_management',
            name='parent_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_services', to='crmapp.service_management'),
        ),
        migrations.AlterField(
            model_name='service_management',
            name='contract_type',
            field=models.CharField(choices=[('One Time', 'One Time'), ('AMC', 'AMC'), ('Warranty', 'Warranty'), ('Complaint', 'Complaint')], default='NOT SELECTED', max_length=50),
        ),
    ]
