# Generated by Django 5.0 on 2025-05-26 05:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0007_invoiceterm_quotationterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotation_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_checkbox', models.BooleanField(default=False)),
                ('gst_status', models.CharField(default='NON-GST', max_length=10)),
                ('total_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price_with_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract_type', models.CharField(choices=[('One Time', 'One Time'), ('AMC', 'AMC'), ('Warranty', 'Warranty')], default='NOT SELECTED', max_length=50)),
                ('contract_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='NOT SELECTED', max_length=100)),
                ('property_type', models.TextField(blank=True, null=True)),
                ('warranty_period', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(default='Null', max_length=100)),
                ('city', models.CharField(default='Null', max_length=100)),
                ('pincode', models.CharField(default='000000', max_length=6)),
                ('address', models.TextField(default='Null')),
                ('gps_location', models.URLField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('frequency_count', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('Fortnight', 'Fortnight'), ('Weekly', 'Weekly'), ('Daily', 'Daily')], default='NOT SELECTED', max_length=50)),
                ('payment_terms', models.CharField(default='100% Advance payment OR Whatever mutually Decided', editable=False, max_length=200)),
                ('sales_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_person_contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('delivery_time', models.TimeField(default=django.utils.timezone.now)),
                ('lead_date', models.DateField(default=django.utils.timezone.now)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details')),
                ('selected_services', models.ManyToManyField(related_name='quotation_services', to='crmapp.product')),
                ('technician', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.technicianprofile')),
            ],
        ),
    ]
