# Generated by Django 5.1.1 on 2025-10-13 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_technicianprofile_branch_alter_userprofile_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead_management',
            name='old_branch',
        ),
        migrations.AddField(
            model_name='lead_management',
            name='old_salesperson_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_manager', to='crmapp.branch'),
        ),
        migrations.AlterField(
            model_name='customer_details',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_details', to='crmapp.branch'),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.branch'),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crmapp.salesperson'),
        ),
        migrations.AlterField(
            model_name='operationperson',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_person', to='crmapp.branch'),
        ),
        migrations.AlterField(
            model_name='operationperson',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_person', to='crmapp.branch'),
        ),
    ]
