# Generated by Django 5.2.3 on 2026-01-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_product_description_product_standard_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='standard_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
