# Generated by Django 5.0 on 2025-05-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_quotation_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation_management',
            name='contract_status',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='warranty_period',
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='customer_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='secondary_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='quotation_management',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation_management',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotation_management',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
