# Generated by Django 5.1.1 on 2025-10-13 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_remove_lead_management_old_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='branch_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='crmapp.branchmanager'),
        ),
    ]
