# Generated by Django 5.0 on 2025-05-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_remove_quotation_management_contract_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation_management',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='frequency_count',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='lead_date',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='sales_person_contact_no',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='sales_person_name',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='service_date',
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='subject',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
