# Generated by Django 5.2.3 on 2026-02-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_alter_product_standard_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='sourceoflead',
            field=models.CharField(choices=[('Google', 'Google'), ('Justdial', 'Justdial'), ('Indiamart', 'IndiaMart'), ('TradeIndia', 'TradeIndia'), ('Renewal', 'Renewal'), ('Customer Reference', 'Customer Reference'), ('BNI', 'BNI'), ('Lionsclub', 'Lions Club'), ('Employee Reference', 'Employee Reference'), ('Others', 'Others'), ('Landing Page', 'Landing Page')], default='NOT SELECTED', max_length=200),
        ),
    ]
