# Generated by Django 5.0 on 2025-05-26 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_remove_quotation_management_delivery_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation_management',
            name='technician',
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='quotation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='terms_and_conditions',
            field=models.ManyToManyField(blank=True, to='crmapp.quotationterm'),
        ),
    ]
