# Generated by Django 5.1.1 on 2025-10-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_lead_management_branch_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='contactperson',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
