# Generated by Django 4.2 on 2026-03-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_alter_lead_management_sourceoflead'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service_management',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
