# Generated by Django 4.2 on 2026-03-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0011_service_management_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='sales_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
