# Generated by Django 4.2 on 2026-03-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0012_service_management_sales_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_management',
            name='sales_person_email',
        ),
    ]
