# Generated by Django 5.0 on 2025-05-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0012_rename_gst_checkbox_quotation_management_apply_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation_management',
            name='gst_status',
            field=models.CharField(choices=[('GST', 'GST'), ('NON-GST', 'Non-GST')], default='NON-GST', max_length=10),
        ),
        migrations.AlterField(
            model_name='quotation_management',
            name='total_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotation_management',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotation_management',
            name='total_price_with_gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
