# Generated by Django 5.1.1 on 2025-10-16 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crmapp', '0012_lead_management_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation_management',
            name='contact_by',
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='contact_by_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='contact_by_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
