# Generated by Django 4.2 on 2026-03-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0013_remove_service_management_sales_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='sales_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
