# Generated by Django 5.1.1 on 2025-10-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0013_remove_quotation_management_contact_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation_management',
            name='contact_by_content_type',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='contact_by_object_id',
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='contact_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
