# Generated by Django 5.0 on 2025-05-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0013_alter_quotation_management_gst_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation_management',
            name='gst_status',
            field=models.CharField(default='NON-GST', max_length=10),
        ),
        migrations.AlterField(
            model_name='quotation_management',
            name='total_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quotation_management',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quotation_management',
            name='total_price_with_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
