# Generated by Django 5.2.3 on 2026-03-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0014_service_management_sales_person_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name']},
        ),
    ]
