# Generated by Django 5.0 on 2025-05-30 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0015_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation_management',
            name='gst_number',
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.branch'),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='gst_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
