# Generated by Django 4.2 on 2026-03-28 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0015_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequiredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_items', to='crmapp.product')),
            ],
        ),
    ]
