# Generated by Django 5.0.7 on 2026-05-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_serviceproduct_created_at'),
        ('crmapp', '0015_alter_product_options'),
    ]

    operations = [
    ]
