# Generated by Django 4.2 on 2026-03-31 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0016_productrequireditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.productrequireditem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.service_management')),
            ],
        ),
    ]
