# Generated by Django 5.0 on 2025-05-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0016_remove_quotation_management_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation_management',
            name='gst_number',
            field=models.CharField(blank=True, help_text='Enter 15-digit GSTIN (optional)', max_length=15, null=True),
        ),
    ]
