# Generated by Django 4.2 on 2026-03-31 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0017_serviceproductitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceProductItem',
        ),
    ]
