# Generated by Django 5.0 on 2025-06-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0017_quotation_management_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='shifttopartyaddress',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='customer_details',
            name='soldtopartyaddress',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='customeraddress',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='company_address',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='workallocation',
            name='customer_address',
            field=models.CharField(max_length=1000),
        ),
    ]
