# Generated by Django 5.0 on 2025-06-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0018_alter_customer_details_shifttopartyaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workallocation',
            name='customer_fname',
        ),
        migrations.RemoveField(
            model_name='workallocation',
            name='customer_lname',
        ),
        migrations.AddField(
            model_name='workallocation',
            name='fullname',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
