# Generated by Django 4.2 on 2026-03-31 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0018_delete_serviceproductitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('required_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.productrequireditem')),
                ('service_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_items', to='crmapp.serviceproduct')),
            ],
        ),
    ]
