# Generated by Django 5.0 on 2025-06-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0019_remove_workallocation_customer_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='branch',
            field=models.CharField(choices=[('Bhiwandi', 'Bhiwandi'), ('Indore', 'Indore'), ('Hyderabad', 'Hyderabad'), ('Nagpur', 'Nagpur'), ('Amravti', 'Amravti'), ('Aurangabad', 'Aurangabad'), ('Baramati', 'Baramati'), ('Pune', 'Pune'), ('Hyderabad', 'Hyderabad')], default='NA', max_length=10),
        ),
    ]
