# Generated by Django 5.2.3 on 2026-04-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0019_serviceproductitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
