# Generated by Django 5.2.3 on 2026-04-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0020_service_management_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='amc_group',
            field=models.CharField(blank=True, help_text='Same AMC ke liye same group id', max_length=100, null=True),
        ),
    ]
