# Generated by Django 5.0 on 2025-06-03 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0021_alter_lead_management_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='branch',
            field=models.CharField(choices=[('Bhiwandi', 'Bhiwandi'), ('Indore', 'Indore'), ('Hyderabad', 'Hyderabad'), ('Nagpur', 'Nagpur'), ('Amravti', 'Amravti'), ('Aurangabad', 'Aurangabad'), ('Baramati', 'Baramati'), ('Pune', 'Pune')], default='NA', max_length=20),
        ),
        migrations.CreateModel(
            name='main_followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_pest_control', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('agency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('onsite_infestation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('infestation_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('typeoflead', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested'), ('Loss of Order', 'Loss of Order')], max_length=100)),
                ('followup_remark', models.CharField(choices=[('Call not received', 'Call not received'), ('Give next Follow up date', 'Give next Follow up date'), ('Call Out of Coverage Area', 'Call Out of Coverage Area')], max_length=255)),
                ('followup_comment', models.TextField()),
                ('next_followup_date', models.DateField()),
                ('order_status', models.CharField(choices=[('Close Win', 'Close Win'), ('Close Loss', 'Close Loss'), ('Not Closed', 'Not Closed')], default='Not Closed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.lead_management')),
            ],
        ),
    ]
