# Generated by Django 4.2 on 2026-04-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0021_service_management_amc_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_management',
            name='amc_group',
        ),
    ]
