# Generated by Django 5.0 on 2025-06-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0022_alter_lead_management_branch_main_followup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead_management',
            options={'verbose_name_plural': 'Lead Management'},
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='customeraddress',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='customeremail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='primarycontact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='secondarycontact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
