# Generated by Django 4.2 on 2026-04-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0022_remove_service_management_amc_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_management',
            name='status',
        ),
        migrations.AddField(
            model_name='service_management',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
