# Generated by Django 5.0 on 2025-06-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0023_alter_lead_management_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_followup',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
