# Generated by Django 4.2 on 2026-04-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0023_remove_service_management_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_management',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='service_management',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
