# Generated by Django 5.2 on 2025-06-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0024_alter_main_followup_next_followup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workallocation',
            name='service',
            field=models.ManyToManyField(to='crmapp.service_management'),
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='workallocation',
            name='technician',
        ),
        migrations.AddField(
            model_name='service_management',
            name='technician',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='crmapp.technicianprofile'),
        ),
        migrations.AddField(
            model_name='workallocation',
            name='technician',
            field=models.ManyToManyField(to='crmapp.technicianprofile'),
        ),
    ]
