# Generated by Django 5.2 on 2025-06-04 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0025_workallocation_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workallocation',
            name='service',
        ),
        migrations.AddField(
            model_name='workallocation',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crmapp.service_management'),
            preserve_default=False,
        ),
    ]
