# Generated by Django 5.2 on 2025-06-04 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0026_remove_workallocation_service_workallocation_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_management',
            name='technician',
        ),
    ]
