# Generated by Django 5.2 on 2025-06-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0027_remove_service_management_technician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techworklist',
            name='work',
        ),
        migrations.AddField(
            model_name='techworklist',
            name='work',
            field=models.ManyToManyField(to='crmapp.workallocation'),
        ),
    ]
