# Generated by Django 5.2 on 2025-06-04 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0029_remove_technicianprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techworklist',
            name='work',
        ),
        migrations.AddField(
            model_name='techworklist',
            name='work',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crmapp.workallocation'),
            preserve_default=False,
        ),
    ]
