# Generated by Django 5.2 on 2025-06-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0030_remove_techworklist_work_techworklist_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techworklist',
            name='work',
        ),
        migrations.AddField(
            model_name='techworklist',
            name='work',
            field=models.ManyToManyField(to='crmapp.workallocation'),
        ),
    ]
