# Generated by Django 5.2 on 2025-06-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0032_service_management_technicians'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_management',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='assigned_services', to='crmapp.technicianprofile'),
        ),
    ]
