# Generated by Django 5.0 on 2025-06-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0033_alter_service_management_technicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation_management',
            name='branch_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='branch_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='branch_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='branch_gst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='branch_pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
