# Generated by Django 5.2 on 2025-06-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0033_alter_service_management_technicians'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_add',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
