# Generated by Django 5.2 on 2025-06-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0034_alter_inventory_add_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_add',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory_summary',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
