# Generated by Django 5.0 on 2025-06-06 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0034_quotation_management_branch_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.branch'),
        ),
    ]
