# Generated by Django 5.0 on 2025-06-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0035_customer_details_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_details',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='branch_address',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='branch_contact',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='branch_email',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='branch_gst',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='branch_pan',
        ),
    ]
