# Generated by Django 5.2 on 2025-06-05 11:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0035_alter_inventory_add_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_summary',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='inventory_summary',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
