# Generated by Django 5.2 on 2025-06-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0036_alter_inventory_summary_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_management',
            name='gst_checkbox',
        ),
        migrations.RemoveField(
            model_name='service_management',
            name='gst_status',
        ),
    ]
