# Generated by Django 5.2 on 2025-06-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0037_remove_service_management_gst_checkbox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_management',
            name='gst_number',
        ),
    ]
