# Generated by Django 5.0 on 2025-06-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0036_remove_customer_details_branch_and_more'),
        ('crmapp', '0038_remove_service_management_gst_number'),
    ]

    operations = [
    ]
