# Generated by Django 5.0 on 2025-06-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0039_merge_20250607_1011'),
        ('crmapp', '0039_merge_20250607_1042'),
    ]

    operations = [
    ]
