# Generated by Django 5.2 on 2025-06-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0041_bankaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='shortcut',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
