# Generated by Django 5.2 on 2025-06-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0042_branch_code_branch_shortcut_branch_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='shortcut',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='branch',
            name='state',
            field=models.CharField(choices=[('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Gujarat', 'Gujarat'), ('Rajasthan', 'Rajasthan'), ('Delhi', 'Delhi'), ('Karnataka', 'Karnataka'), ('Tamil Nadu', 'Tamil Nadu')], max_length=50),
        ),
    ]
