# Generated by Django 5.2 on 2025-06-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0043_alter_branch_code_alter_branch_shortcut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='shortcut',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='branch',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
