# Generated by Django 5.2 on 2025-06-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0044_alter_branch_code_alter_branch_shortcut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation_management',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='product_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='product_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
