# Generated by Django 5.2 on 2025-06-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0045_quotation_management_gst_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation_management',
            name='gst_rate',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='product_unit',
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='product_details_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation_management',
            name='selected_services',
            field=models.ManyToManyField(blank=True, related_name='quotation_services', to='crmapp.product'),
        ),
    ]
