# Generated by Django 5.0 on 2025-06-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0046_remove_quotation_management_gst_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation_management',
            name='contact_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='contact_by_no',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
