# Generated by Django 5.2.3 on 2025-06-13 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0047_quotation_management_contact_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_sac', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_no', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referance_no_and_date', models.CharField(blank=True, max_length=100, null=True)),
                ('other_referance', models.CharField(blank=True, max_length=500, null=True)),
                ('delivery_note', models.CharField(blank=True, max_length=100, null=True)),
                ('modern_terms_of_payment', models.CharField(blank=True, max_length=100, null=True)),
                ('buyers_order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('dated', models.DateField(blank=True, null=True)),
                ('dispatch_doc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_note_date', models.CharField(blank=True, max_length=500, null=True)),
                ('dispatched_through', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=1000, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='crmapp.bankaccounts')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_details', to='crmapp.customer_details')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_invoice', to='crmapp.quotation_management')),
            ],
        ),
    ]
