# Generated by Django 5.2.3 on 2025-06-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0048_taxinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='tax_invoice_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='delivery_note_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
