# Generated by Django 5.2.3 on 2025-06-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0049_taxinvoice_tax_invoice_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxinvoice',
            name='invoice_no',
        ),
    ]
