# Generated by Django 5.2.3 on 2025-06-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0050_remove_taxinvoice_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinvoice',
            name='tax_invoice_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
