# Generated by Django 5.2.3 on 2025-06-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0051_alter_taxinvoice_tax_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation_management',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
