# Generated by Django 5.2.3 on 2025-06-13 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0052_quotation_management_quotation_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxinvoice',
            name='hsn_sac',
        ),
        migrations.CreateModel(
            name='TaxInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crmapp.taxinvoice')),
            ],
        ),
    ]
