# Generated by Django 5.2.3 on 2025-06-14 05:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0054_taxinvoice_service_titel_taxinvoice_shift_gstin_uin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
