# Generated by Django 5.2.3 on 2025-06-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0055_taxinvoice_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinvoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
