# Generated by Django 5.2.3 on 2025-06-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0056_alter_taxinvoiceitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxinvoice',
            name='grand_total',
        ),
    ]
