# Generated by Django 5.2.3 on 2025-06-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0058_taxinvoice_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='primarycontact',
            field=models.BigIntegerField(unique=True),
        ),
    ]
