# Generated by Django 5.2.3 on 2025-06-17 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0059_alter_customer_details_primarycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation_management',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details'),
            preserve_default=False,
        ),
    ]
