# Generated by Django 5.2.3 on 2025-06-17 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0060_quotation_management_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation_management',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details'),
        ),
    ]
