# Generated by Django 5.2.3 on 2025-06-24 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0061_alter_quotation_management_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_invoice_no', models.CharField(blank=True, max_length=100, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_remaining', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('payment_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('previous_due_date', models.DateField(blank=True, null=True)),
                ('payment_rating', models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='payment_attachments/')),
                ('main_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crmapp.taxinvoice')),
            ],
        ),
    ]
