# Generated by Django 5.2.3 on 2025-06-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0062_paymentsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsrecord',
            name='payment_mode',
            field=models.CharField(choices=[('upi', 'UPI'), ('cash', 'CASH'), ('credit_card', 'CREDIT CARD'), ('debit_card', 'DEBIT CARD'), ('net_banking', 'NET BANKING'), ('wallet', 'WALLET'), ('bank_transfer', 'BANK TRANSFER'), ('cheque', 'CHEQUE'), ('pay_later', 'PAY LATER'), ('emi', 'EMI'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('imps', 'IMPS')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
