# Generated by Django 5.2.3 on 2025-06-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0063_paymentsrecord_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsrecord',
            name='payment_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paymentsrecord',
            name='work_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
