# Generated by Django 5.2.3 on 2025-06-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0064_paymentsrecord_payment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation_management',
            name='custom_terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
