# Generated by Django 5.2.3 on 2025-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0065_quotation_management_custom_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsrecord',
            name='base_invoice_ref',
            field=models.CharField(default=1, editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
