# Generated by Django 5.2.3 on 2025-07-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0066_paymentsrecord_base_invoice_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='customersegment',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Industrial', 'Industrial'), ('Commercial', 'Commercial'), ('Institutional', 'Institutional'), ('Irrelevant Leads', 'Irrelevant Leads')], max_length=100),
        ),
    ]
