# Generated by Django 5.2.3 on 2025-07-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0067_alter_lead_management_customersegment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='customersegment',
            field=models.CharField(choices=[('Resedential', 'Resedential'), ('Industrial', 'Industrial'), ('Commercial', 'Commercial'), ('Institutional', 'Institutional'), ('Irrelevant Leads', 'Irrelevant Leads')], max_length=100),
        ),
    ]
