# Generated by Django 5.2.3 on 2025-07-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0069_alter_lead_management_customersegment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='customersegment',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Industrial / Commercial', 'Industrial / Commercial'), ('Institutional', 'Institutional'), ('Irrelevant Leads', 'Irrelevant Leads')], max_length=100),
        ),
    ]
