# Generated by Django 5.2.3 on 2025-07-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0070_alter_lead_management_customersegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='segment',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Industrial / Commercial', 'Industrial / Commercial'), ('Institutional', 'Institutional'), ('Irrelevant Leads', 'Irrelevant Leads')], max_length=100, null=True),
        ),
    ]
