# Generated by Django 5.2.3 on 2025-07-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0071_service_management_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='customer_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='or_contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='or_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='customer_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='or_contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='or_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
