# Generated by Django 5.2.3 on 2025-07-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0072_customer_details_customer_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_details',
            old_name='customersegment',
            new_name='designation',
        ),
    ]
