# Generated by Django 5.2.3 on 2025-07-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0073_rename_customersegment_customer_details_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation_management',
            name='or_contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quotation_management',
            name='or_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
