# Generated by Django 5.2.3 on 2025-07-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0074_quotation_management_or_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation_management',
            name='thank_u_note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
