# Generated by Django 5.2.3 on 2025-07-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0076_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('technician', 'Technician'), ('customer', 'Customer')], max_length=20),
        ),
    ]
