# Generated by Django 5.2.3 on 2025-07-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0077_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_management',
            name='selected_services',
        ),
    ]
