# Generated by Django 5.2.3 on 2025-07-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0078_remove_service_management_selected_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('gst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_with_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_products', to='crmapp.service_management')),
            ],
        ),
        migrations.AddField(
            model_name='service_management',
            name='selected_services',
            field=models.ManyToManyField(related_name='selected_services', through='crmapp.ServiceProduct', to='crmapp.product'),
        ),
    ]
