# Generated by Django 5.2.3 on 2025-07-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0079_serviceproduct_service_management_selected_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='gst_status',
            field=models.CharField(choices=[('GST', 'GST'), ('NON-GST', 'NON-GST')], default='GST', max_length=10),
        ),
    ]
