# Generated by Django 5.2.3 on 2025-07-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0080_service_management_gst_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
