# Generated by Django 5.2.3 on 2025-07-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0081_alter_serviceproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='techworklist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
