# Generated by Django 5.2.3 on 2025-07-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0082_techworklist_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techworklist',
            name='description',
        ),
    ]
