# Generated by Django 5.2.3 on 2025-07-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0083_remove_techworklist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
