# Generated by Django 5.2.3 on 2025-08-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0084_serviceproduct_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation_management',
            name='terms_order',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
