# Generated by Django 5.2.3 on 2025-08-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0085_quotation_management_terms_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation_management',
            name='gst_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
