# Generated by Django 5.2.3 on 2025-08-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0086_alter_quotation_management_gst_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation_management',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='quotation_management',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='quotation_management',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
