# Generated by Django 5.2.3 on 2025-08-13 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0087_alter_quotation_management_cgst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='crmapp.branch'),
            preserve_default=False,
        ),
    ]
