# Generated by Django 5.2.3 on 2025-08-13 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0088_taxinvoice_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinvoice',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_invoice', to='crmapp.quotation_management'),
        ),
    ]
