# Generated by Django 5.2.3 on 2025-08-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0089_alter_taxinvoice_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='gst_type',
            field=models.CharField(blank=True, choices=[('CGST_SGST', 'CGST + SGST'), ('IGST', 'IGST')], max_length=20, null=True),
        ),
    ]
