# Generated by Django 5.2.3 on 2025-08-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0090_taxinvoice_gst_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='declaration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
