# Generated by Django 5.2.3 on 2025-08-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0091_taxinvoice_declaration_taxinvoice_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='bill_to_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='ship_to_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
