# Generated by Django 5.2.3 on 2025-08-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0092_taxinvoice_bill_to_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pest Control', 'Pest Control'), ('Fumigation', 'Fumigation'), ('Product Sale', 'Product Sale')], default='NULL', max_length=50),
        ),
    ]
