# Generated by Django 5.2.3 on 2025-08-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0093_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxinvoice',
            old_name='declaration',
            new_name='terms_of_delivery',
        ),
    ]
