# Generated by Django 5.2.3 on 2025-08-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0094_rename_declaration_taxinvoice_terms_of_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='shift_pan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='sold_pan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='shift_gstin_uin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='sold_gstin_uin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
