# Generated by Django 5.2.3 on 2025-08-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0095_taxinvoice_shift_pan_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoiceitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
