# Generated by Django 5.2.3 on 2025-08-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0096_taxinvoiceitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation_management',
            name='city',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='customer_full_name',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='gps_location',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='secondary_contact_no',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='secondary_email',
        ),
        migrations.RemoveField(
            model_name='quotation_management',
            name='state',
        ),
    ]
