# Generated by Django 5.2.3 on 2025-09-01 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0097_remove_quotation_management_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='salesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crmapp.salesperson'),
        ),
    ]
