# Generated by Django 5.2.3 on 2025-09-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0098_alter_lead_management_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='techworklist',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
