# Generated by Django 5.2.3 on 2025-09-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0099_techworklist_is_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techworklist',
            name='work',
            field=models.ManyToManyField(related_name='work', to='crmapp.workallocation'),
        ),
    ]
