# Generated by Django 5.2.3 on 2025-09-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0100_alter_techworklist_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='techworklist',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='techworklist',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('UPI+Cash', 'UPI Cash')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='techworklist',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Full Payment', 'Full Payment'), ('Half Payment', 'Half Payment')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='techworklist',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
