# Generated by Django 5.2.3 on 2025-09-05 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0101_techworklist_next_due_date_techworklist_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workallocation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_allocations', to='crmapp.service_management'),
        ),
    ]
