# Generated by Django 5.2.3 on 2025-09-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0102_alter_workallocation_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name (eg.Lead-hot)', max_length=200)),
                ('message_type', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('category', models.CharField(choices=[('lead', 'Lead'), ('service', 'Service Schedule'), ('quotation', 'Quotation'), ('invoice', 'Invoice'), ('payment', 'Payment Tracker')], max_length=50)),
                ('lead_status', models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('not_insterested', 'Not Interested'), ('loss_of_order', 'Loss of Order')], max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message Templates',
                'verbose_name_plural': 'Message Templates',
                'db_table': 'MessageTemplates',
            },
        ),
    ]
