# Generated by Django 5.2.3 on 2025-09-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0103_messagetemplates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetemplates',
            options={},
        ),
        migrations.AlterModelTable(
            name='messagetemplates',
            table=None,
        ),
    ]
