# Generated by Django 5.2.3 on 2025-09-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0104_alter_messagetemplates_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='service_subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
