# Generated by Django 5.2.3 on 2025-09-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0105_service_management_service_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplates',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/'),
        ),
    ]
