# Generated by Django 5.2.3 on 2025-09-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0107_alter_messagetemplates_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplates',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('not interested', 'Not Interested'), ('loss of order', 'Loss of Order')], max_length=50, null=True),
        ),
    ]
