# Generated by Django 5.2.3 on 2025-09-23 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0108_alter_messagetemplates_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_management',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.branch'),
        ),
    ]
