# Generated by Django 5.2.3 on 2025-09-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0109_service_management_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsrecord',
            name='last_alert_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
