# Generated by Django 5.2.3 on 2025-09-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0110_paymentsrecord_last_alert_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='primaryemail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
