# Generated by Django 5.2.3 on 2025-10-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0111_alter_customer_details_primaryemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
