# Generated by Django 5.2.3 on 2025-10-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0113_alter_lead_management_branch_alter_userprofile_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead_management',
            old_name='branch',
            new_name='old_branch',
        ),
    ]
