# Generated by Django 5.2.3 on 2025-10-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0114_rename_branch_lead_management_old_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.branch'),
        ),
    ]
