# Generated by Django 5.2.3 on 2025-10-06 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0115_lead_management_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_person', to='crmapp.branch'),
            preserve_default=False,
        ),
    ]
