# Generated by Django 5.2.3 on 2025-10-07 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0116_salesperson_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_details', to='crmapp.branch'),
            preserve_default=False,
        ),
    ]
