# Generated by Django 5.2.3 on 2025-10-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0117_customer_details_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='co_ordinator',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
