# Generated by Django 5.2.3 on 2025-10-09 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0119_alter_userprofile_role_operationperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='technician', to='crmapp.branch'),
            preserve_default=False,
        ),
    ]
