# Generated by Django 5.2.3 on 2026-05-05 04:53

import amc.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crmapp', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(default=amc.models.generate_contract_number, editable=False, max_length=50, unique=True)),
                ('amc_type', models.CharField(choices=[('Comprehensive', 'Comprehensive'), ('Non-Comprehensive', 'Non-Comprehensive'), ('Warranty', 'Warranty')], default='Comprehensive', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(editable=False)),
                ('frequency', models.CharField(help_text='1–12 OR Weekly / Fortnight / Daily', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('per_visit_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('default_customer_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('default_customer_address', models.TextField(blank=True, null=True)),
                ('default_gps_location', models.URLField(blank=True, null=True)),
                ('default_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('default_payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Cash', 'Cash'), ('Online', 'Online')], default='Pending', max_length=20)),
                ('default_work_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('renewal_status', models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_RENEWED', 'Not Renewed')], default='PENDING', max_length=20)),
                ('renewal_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.customer_details')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.service_management')),
                ('technicians', models.ManyToManyField(blank=True, related_name='amc_contracts', to='crmapp.technicianprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AMCServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('reminder_sent', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='amc.amccontract')),
            ],
        ),
        migrations.CreateModel(
            name='AMCServiceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('crm_service_created_at', models.DateTimeField(blank=True, null=True)),
                ('auto_allocation_done', models.BooleanField(default=False)),
                ('allocation_status', models.CharField(choices=[('PENDING', 'Pending'), ('ALLOCATED', 'Allocated'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('allocation_cancelled_reason', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('rescheduled_from', models.DateField(blank=True, null=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='amc.amccontract')),
                ('crm_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_service_visits', to='crmapp.service_management')),
                ('technicians', models.ManyToManyField(blank=True, related_name='amc_visits', to='crmapp.technicianprofile')),
            ],
        ),
    ]
