# Generated by Django 5.2.3 on 2026-05-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcservicevisit',
            name='auto_allocation_done',
            field=models.BooleanField(default=False),
        ),
    ]
