# Generated by Django 5.2.3 on 2026-05-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amccontract',
            name='frequency',
            field=models.CharField(blank=True, help_text='(Deprecated) Use product-wise frequencies instead', max_length=20, null=True),
        ),
    ]
