# Generated by Django 5.2.3 on 2025-12-09 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0001_initial'),
        ('crmapp', '0003_branch_is_head_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='amc_type',
            field=models.CharField(choices=[('Comprehensive', 'Comprehensive'), ('Non-Comprehensive', 'Non-Comprehensive'), ('Warranty', 'Warranty'), ('One-Time', 'One-Time')], default='Comprehensive', max_length=50),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='renewal_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.service_management'),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='service_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='amccontract',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
