# Generated by Django 5.2.3 on 2026-05-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0002_amcservicevisit_auto_allocation_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcservicevisit',
            name='crm_service_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
