# Generated by Django 5.2.3 on 2025-12-09 11:16

import amc.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0002_amccontract_amc_type_and_more'),
        ('crmapp', '0003_branch_is_head_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amccontract',
            name='renewal_reminder_date',
        ),
        migrations.RemoveField(
            model_name='amccontract',
            name='service_count',
        ),
        migrations.RemoveField(
            model_name='amccontract',
            name='technicians',
        ),
        migrations.AddField(
            model_name='amccontract',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.technicianprofile'),
        ),
        migrations.AlterField(
            model_name='amccontract',
            name='amc_type',
            field=models.CharField(choices=[('Comprehensive', 'Comprehensive'), ('Non-Comprehensive', 'Non-Comprehensive'), ('Warranty', 'Warranty')], default='Comprehensive', max_length=50),
        ),
        migrations.AlterField(
            model_name='amccontract',
            name='contract_number',
            field=models.CharField(default=amc.models.generate_contract_number, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='amccontract',
            name='per_visit_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amccontract',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.service_management'),
        ),
        migrations.AlterField(
            model_name='amccontract',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
