# Generated by Django 5.2.3 on 2026-05-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0002_alter_amccontract_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amccontract',
            name='contract_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
