# Generated by Django 5.2.3 on 2026-05-05 09:57

import amc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_alter_amccontract_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amccontract',
            name='contract_number',
            field=models.CharField(default=amc.models.generate_contract_number, editable=False, max_length=50, unique=True),
        ),
    ]
