# Generated by Django 5.2.3 on 2025-12-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_remove_amccontract_renewal_reminder_date_and_more'),
        ('crmapp', '0003_branch_is_head_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amccontract',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='amcservicevisit',
            name='technician',
        ),
        migrations.AddField(
            model_name='amccontract',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='amc_contracts', to='crmapp.technicianprofile'),
        ),
        migrations.AddField(
            model_name='amcservicevisit',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='amc_visits', to='crmapp.technicianprofile'),
        ),
    ]
