# Generated by Django 5.2.3 on 2025-12-10 06:37
# Fixed: Removed the RemoveField(amcservicevisit, technician) operation because
# amcservicevisit never had a 'technician' ForeignKey in the bharat-new branch migration chain.
# The amcservicevisit model only had 'technicians' (M2M) which is handled separately.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_remove_amccontract_renewal_reminder_date_and_more'),
        ('crmapp', '0003_branch_is_head_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amccontract',
            name='technician',
        ),
        # NOTE: RemoveField(amcservicevisit, technician) was intentionally removed here
        # because amcservicevisit never had a 'technician' FK in this migration branch.
        # Only amccontract had it (added in 0003 and removed here).
        migrations.AddField(
            model_name='amccontract',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='amc_contracts', to='crmapp.technicianprofile'),
        ),
        migrations.AddField(
            model_name='amcservicevisit',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='amc_visits', to='crmapp.technicianprofile'),
        ),
    ]
