# Generated by Django 5.2.3 on 2026-09-22 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_amcservicevisit_crm_service_created_at'),
        ('crmapp', '0007_customer_details_or_email_lead_management_or_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcservicevisit',
            name='complaint_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amcservicevisit',
            name='complaint_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_amc_visits', to='crmapp.service_management'),
        ),
        migrations.AddField(
            model_name='amcservicevisit',
            name='has_complaint',
            field=models.BooleanField(default=False),
        ),
    ]
