# Generated by Django 5.2.3 on 2026-05-05 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0004_alter_amccontract_contract_number'),
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcservicevisit',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_visits', to='crmapp.product'),
        ),
    ]
