# Generated by Django 4.2.11 on 2025-12-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0004_remove_amccontract_technician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='expiry_mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='reminder_15_days_sent',
            field=models.BooleanField(default=False),
        ),
    ]
