# Generated by Django 5.2.3 on 2026-05-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0005_amcservicevisit_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amcservicevisit',
            name='auto_allocation_done',
        ),
        migrations.RemoveField(
            model_name='amcservicevisit',
            name='crm_service_created_at',
        ),
        migrations.RemoveField(
            model_name='amcservicevisit',
            name='next_visit_date',
        ),
        migrations.RemoveField(
            model_name='amcservicevisit',
            name='rescheduled_from',
        ),
    ]
