# Generated by Django 4.2.11 on 2025-12-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0005_amccontract_expiry_mail_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='renewal_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='renewal_status',
            field=models.CharField(choices=[('NONE', 'No Action'), ('REQUESTED', 'Renewal Requested'), ('APPROVED', 'Renewal Approved'), ('REJECTED', 'Renewal Rejected'), ('NOT_RENEWED', 'Not Renewed')], default='NONE', max_length=20),
        ),
    ]
