# Generated by Django 4.2.11 on 2025-12-23 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0006_amccontract_renewal_requested_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('reminder_sent', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='amc.amccontract')),
            ],
        ),
    ]
