# Generated by Django 4.2.11 on 2025-12-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0007_amcserviceschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcservicevisit',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amcservicevisit',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
