# Generated by Django 4.2.11 on 2026-01-05 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0008_amcservicevisit_completed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amcservicevisit',
            old_name='service_date',
            new_name='visit_date',
        ),
        migrations.RemoveField(
            model_name='amccontract',
            name='expiry_mail_sent',
        ),
        migrations.RemoveField(
            model_name='amccontract',
            name='reminder_15_days_sent',
        ),
        migrations.RemoveField(
            model_name='amccontract',
            name='renewal_requested_at',
        ),
        migrations.RemoveField(
            model_name='amccontract',
            name='renewal_status',
        ),
        migrations.RemoveField(
            model_name='amcservicevisit',
            name='next_visit_date',
        ),
        migrations.AddField(
            model_name='amccontract',
            name='frequency',
            field=models.PositiveIntegerField(default=4, help_text='Number of services per year (1, 2, 3, 4, 6, 12)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amcservicevisit',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='amc.amcserviceschedule'),
        ),
        migrations.AlterField(
            model_name='amccontract',
            name='end_date',
            field=models.DateField(editable=False),
        ),
    ]
