# Generated by Django 4.2.11 on 2026-01-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0009_rename_service_date_amcservicevisit_visit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amccontract',
            name='frequency',
            field=models.CharField(help_text='1–12 OR Weekly / Fortnight / Daily', max_length=20),
        ),
    ]
