# Generated by Django 4.2.11 on 2026-01-06 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_branch_is_head_office'),
        ('amc', '0010_alter_amccontract_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amcservicevisit',
            old_name='visit_date',
            new_name='service_date',
        ),
        migrations.RemoveField(
            model_name='amcservicevisit',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='amcservicevisit',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='amcservicevisit',
            name='schedule',
        ),
        migrations.AddField(
            model_name='amcservicevisit',
            name='crm_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_service_visits', to='crmapp.service_management'),
        ),
        migrations.AddField(
            model_name='amcservicevisit',
            name='next_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
