# Generated by Django 4.2.11 on 2026-01-06 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0011_rename_visit_date_amcservicevisit_service_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcservicevisit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amcservicevisit',
            name='rescheduled_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amcservicevisit',
            name='amc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='amc.amccontract'),
        ),
    ]
