# Generated by Django 4.2.11 on 2026-01-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0012_amcservicevisit_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='renewal_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='renewal_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_RENEWED', 'Not Renewed')], default='PENDING', max_length=20),
        ),
    ]
