# Generated by Django 4.2.11 on 2026-01-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0013_amccontract_renewal_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='default_customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='default_customer_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='default_gps_location',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='default_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='default_payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cash', 'Cash'), ('Online', 'Online')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='default_work_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
