# Generated by Django 4.2.11 on 2026-01-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0014_amccontract_default_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcservicevisit',
            name='allocation_cancelled_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amcservicevisit',
            name='allocation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ALLOCATED', 'Allocated'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
