# Generated by Django 4.2.11 on 2026-01-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0015_amcservicevisit_allocation_cancelled_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcservicevisit',
            name='crm_service_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
