# Generated by Django 4.2.11 on 2026-01-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0016_amcservicevisit_crm_service_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcservicevisit',
            name='auto_allocation_done',
            field=models.BooleanField(default=False),
        ),
    ]
