# Generated by Django 4.2 on 2026-04-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0017_amcservicevisit_auto_allocation_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcserviceschedule',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
