# Generated by Django 5.2.3 on 2026-04-19 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0018_amcserviceschedule_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcserviceschedule',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='amc.amcservicevisit'),
        ),
    ]
