# Generated by Django 5.2.3 on 2026-04-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0019_amcserviceschedule_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amcserviceschedule',
            name='visit',
        ),
    ]
